version: 2.1
workflows:
  starter:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - main

executors:
  my-executor:
    machine:
      image: ubuntu-2204:edge

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: echo ${CIRCLE_BUILD_NUM}
      - run: docker run --workdir /appbuild -v $(pwd):/appbuild node:22-alpine3.19 /bin/sh build.sh
      - run: docker build . -t 169533462518.dkr.ecr.us-east-2.amazonaws.com/todo-web:1.0.${CIRCLE_BUILD_NUM}
      - run: docker image ls
      - run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 169533462518.dkr.ecr.us-east-2.amazonaws.com
      - run: docker image push 169533462518.dkr.ecr.us-east-2.amazonaws.com/todo-web:1.0.${CIRCLE_BUILD_NUM}

