name: build todo web
run-name: build todo web
on:
  pull_request:
    branches:
      - master
      - main
    types:
      - closed

jobs:
  docker_login:
    runs-on: ubuntu-latest
    name: build accounting web project
    if: github.event.pull_request.merged == true
    steps:
      - name: code checkout
        uses: actions/checkout@v6

      - name: build
        run: |
          echo the build number is: ${GITHUB_RUN_NUMBER}
          docker run --workdir /application -v $(pwd):/application node:24-alpine3.22 /bin/sh build.sh
          docker build . -t 169533462518.dkr.ecr.us-east-2.amazonaws.com/todo-web:1.0.11${GITHUB_RUN_NUMBER}
          docker image ls

      - name: docker login
        run: |
          val=$(AWS_ACCESS_KEY_ID=${{secrets.DOCKER_AWS_KEY}} AWS_SECRET_ACCESS_KEY=${{secrets.DOCKER_AWS_SECRET}} aws ecr get-login-password --region us-east-2)
          echo "val=$val" >> $GITHUB_ENV
          echo $val | docker login --username AWS --password-stdin 169533462518.dkr.ecr.us-east-2.amazonaws.com
          docker image ls

      - name: docker push
        run: |
          docker image push 169533462518.dkr.ecr.us-east-2.amazonaws.com/todo-web:1.0.11${GITHUB_RUN_NUMBER}
          echo docker pushed successfully
